// Code generated by protoc-gen-go.
// source: github.com/google/battery-historian/pb/usagestats_proto/android_battery_usage.proto
// DO NOT EDIT!

/*
Package usagestats is a generated protocol buffer package.

It is generated from these files:
	github.com/google/battery-historian/pb/usagestats_proto/android_battery_usage.proto
	github.com/google/battery-historian/pb/usagestats_proto/android_package_info.proto

It has these top-level messages:
	SystemInfo
	PackageInfo
*/
package usagestats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type SystemInfo struct {
	// Installed Package List
	InstalledPackages []*PackageInfo `protobuf:"bytes,1,rep,name=installed_packages" json:"installed_packages,omitempty"`
	// e.g. hammerhead-userdebug L MASTER eng.xx... dev-keys Build
	BuildDisplay *string `protobuf:"bytes,2,opt,name=build_display" json:"build_display,omitempty"`
	// e.g. google/hammerhead/hammerhead:L/MASTER/
	//        eng.abcd.20140304.184123:userdebug/dev-keys
	BuildFingerprint *string `protobuf:"bytes,3,opt,name=build_fingerprint" json:"build_fingerprint,omitempty"`
	// Bootloader version e.g. HHZ11k
	Bootloader *string `protobuf:"bytes,4,opt,name=bootloader" json:"bootloader,omitempty"`
	// e.g. T-Mobile
	NetworkOperator *string `protobuf:"bytes,5,opt,name=network_operator" json:"network_operator,omitempty"`
	// e.g. userdebug
	BuildType *string `protobuf:"bytes,6,opt,name=build_type" json:"build_type,omitempty"`
	// e.g. hammerhead
	Device *string `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	// e.g. M8974A-2.0.50.1.02
	BasebandRadio *string `protobuf:"bytes,8,opt,name=baseband_radio" json:"baseband_radio,omitempty"`
	// e.g. hammerhead
	Hardware *string `protobuf:"bytes,9,opt,name=hardware" json:"hardware,omitempty"`
	// Checkin/OTA groups for the device
	//    e.g. auto.droidfood, auto.googlefood.lmp
	Groups []string `protobuf:"bytes,10,rep,name=groups" json:"groups,omitempty"`
	// e.g. 22
	SdkVersion *int32 `protobuf:"varint,11,opt,name=sdk_version" json:"sdk_version,omitempty"`
	// e.g. ES
	CountryCode *string `protobuf:"bytes,12,opt,name=country_code" json:"country_code,omitempty"`
	// e.g. Europe/London
	TimeZone         *string `protobuf:"bytes,13,opt,name=time_zone" json:"time_zone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SystemInfo) Reset()                    { *m = SystemInfo{} }
func (m *SystemInfo) String() string            { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()               {}
func (*SystemInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SystemInfo) GetInstalledPackages() []*PackageInfo {
	if m != nil {
		return m.InstalledPackages
	}
	return nil
}

func (m *SystemInfo) GetBuildDisplay() string {
	if m != nil && m.BuildDisplay != nil {
		return *m.BuildDisplay
	}
	return ""
}

func (m *SystemInfo) GetBuildFingerprint() string {
	if m != nil && m.BuildFingerprint != nil {
		return *m.BuildFingerprint
	}
	return ""
}

func (m *SystemInfo) GetBootloader() string {
	if m != nil && m.Bootloader != nil {
		return *m.Bootloader
	}
	return ""
}

func (m *SystemInfo) GetNetworkOperator() string {
	if m != nil && m.NetworkOperator != nil {
		return *m.NetworkOperator
	}
	return ""
}

func (m *SystemInfo) GetBuildType() string {
	if m != nil && m.BuildType != nil {
		return *m.BuildType
	}
	return ""
}

func (m *SystemInfo) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *SystemInfo) GetBasebandRadio() string {
	if m != nil && m.BasebandRadio != nil {
		return *m.BasebandRadio
	}
	return ""
}

func (m *SystemInfo) GetHardware() string {
	if m != nil && m.Hardware != nil {
		return *m.Hardware
	}
	return ""
}

func (m *SystemInfo) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SystemInfo) GetSdkVersion() int32 {
	if m != nil && m.SdkVersion != nil {
		return *m.SdkVersion
	}
	return 0
}

func (m *SystemInfo) GetCountryCode() string {
	if m != nil && m.CountryCode != nil {
		return *m.CountryCode
	}
	return ""
}

func (m *SystemInfo) GetTimeZone() string {
	if m != nil && m.TimeZone != nil {
		return *m.TimeZone
	}
	return ""
}

func init() {
	proto.RegisterType((*SystemInfo)(nil), "usagestats.SystemInfo")
}

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x91, 0x4d, 0x6e, 0xea, 0x30,
	0x14, 0x85, 0x05, 0x3c, 0x78, 0xe4, 0xf2, 0x23, 0xc8, 0xfb, 0xa9, 0xdb, 0x11, 0xea, 0x88, 0x49,
	0x13, 0xa9, 0x5d, 0x45, 0x67, 0x55, 0x59, 0x80, 0x65, 0xc7, 0x97, 0x60, 0x11, 0x7c, 0x2d, 0xdb,
	0x01, 0xa5, 0x7b, 0xeb, 0xde, 0xea, 0x9a, 0x16, 0x16, 0xd0, 0x61, 0xbe, 0xf3, 0x9d, 0x1b, 0x1d,
	0x19, 0x36, 0xb5, 0x0e, 0xbb, 0x56, 0x16, 0x15, 0x1d, 0xca, 0x9a, 0xa8, 0x6e, 0xb0, 0x94, 0x22,
	0x04, 0x74, 0xdd, 0xc3, 0x4e, 0xfb, 0x40, 0x4e, 0x0b, 0x53, 0x5a, 0x59, 0xb6, 0x5e, 0xd4, 0xe8,
	0x83, 0x08, 0x9e, 0x5b, 0x47, 0x81, 0x4a, 0x61, 0x94, 0x23, 0xad, 0xf8, 0x97, 0xcd, 0x93, 0x50,
	0xa4, 0x2c, 0x87, 0xab, 0x7d, 0xf7, 0xfa, 0xd3, 0x1f, 0x58, 0x51, 0xed, 0x63, 0xc4, 0xb5, 0xd9,
	0xd2, 0xf9, 0xfe, 0xfd, 0x7b, 0x1f, 0x60, 0xd3, 0xf9, 0x80, 0x87, 0xe7, 0x08, 0xf3, 0x27, 0xc8,
	0xb5, 0x89, 0xd5, 0xa6, 0xc1, 0x8b, 0xee, 0x59, 0x6f, 0x35, 0x58, 0x4f, 0x1e, 0x6f, 0x8a, 0xeb,
	0xe1, 0xe2, 0xe5, 0x9c, 0xa5, 0xd2, 0x3f, 0x98, 0xc9, 0x56, 0x37, 0x8a, 0x2b, 0xed, 0x6d, 0x23,
	0x3a, 0xd6, 0x5f, 0xf5, 0xd6, 0x59, 0x7e, 0x0b, 0xcb, 0x33, 0xde, 0x6a, 0x53, 0xa3, 0xb3, 0x4e,
	0x9b, 0xc0, 0x06, 0x29, 0xca, 0x01, 0x24, 0x51, 0x68, 0x48, 0x28, 0x74, 0xec, 0x57, 0x62, 0x0c,
	0x16, 0x06, 0xc3, 0x89, 0xdc, 0x9e, 0x93, 0x45, 0x27, 0xe2, 0x1e, 0x36, 0xbc, 0xd8, 0xe9, 0x50,
	0xe8, 0x2c, 0xb2, 0x51, 0x62, 0x73, 0x18, 0x29, 0x3c, 0xea, 0x0a, 0xd9, 0xef, 0xf4, 0xfd, 0x1f,
	0xe6, 0x52, 0x78, 0x94, 0x71, 0x2a, 0x77, 0x42, 0x69, 0x62, 0xe3, 0xc4, 0x17, 0x30, 0xde, 0x09,
	0xa7, 0x4e, 0xc2, 0x21, 0xcb, 0xbe, 0x9b, 0xb5, 0xa3, 0xd6, 0x7a, 0x06, 0x71, 0x56, 0x96, 0xff,
	0x81, 0x89, 0x57, 0x7b, 0x7e, 0x44, 0xe7, 0x35, 0x19, 0x36, 0x89, 0xd2, 0x30, 0xff, 0x0b, 0xd3,
	0x8a, 0x5a, 0x13, 0xe2, 0x6b, 0x54, 0xa4, 0x90, 0x4d, 0x53, 0x75, 0x09, 0x59, 0xd0, 0x07, 0xe4,
	0x6f, 0x64, 0x90, 0xcd, 0x3e, 0xd1, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x81, 0x6b, 0x2a,
	0xf5, 0x01, 0x00, 0x00,
}
