// Code generated by protoc-gen-go.
// source: github.com/google/battery-historian/pb/session_proto/session.proto
// DO NOT EDIT!

/*
Package session is a generated protocol buffer package.

It is generated from these files:
	github.com/google/battery-historian/pb/session_proto/session.proto

It has these top-level messages:
	Checkin
*/
package session

import proto "github.com/golang/protobuf/proto"
import math "math"
import usagestats1 "github.com/google/battery-historian/pb/usagestats_proto"
import usagestats "github.com/google/battery-historian/pb/usagestats_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Aggregated checkin stats that we will use to compute deltas.
type Checkin struct {
	AndroidId *int64 `protobuf:"varint,1,opt,name=android_id" json:"android_id,omitempty"`
	// Build fingerprint
	BuildFingerprint *string `protobuf:"bytes,2,opt,name=build_fingerprint" json:"build_fingerprint,omitempty"`
	// Device
	Device *string `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	// Timestamp of measurement
	BucketSnapshotMsec *int64 `protobuf:"varint,4,opt,name=bucket_snapshot_msec" json:"bucket_snapshot_msec,omitempty"`
	// Duration of the collection
	BucketDurationMsec *int64 `protobuf:"varint,5,opt,name=bucket_duration_msec" json:"bucket_duration_msec,omitempty"`
	// Checkin
	Checkin *string `protobuf:"bytes,6,opt,name=checkin" json:"checkin,omitempty"`
	// Installed packages
	Packages []*usagestats.PackageInfo `protobuf:"bytes,7,rep,name=packages" json:"packages,omitempty"`
	// Checkin/OTA groups for the device
	//    e.g. auto.droidfood, auto.googlefood.lmp
	Groups []string `protobuf:"bytes,10,rep,name=groups" json:"groups,omitempty"`
	// System info uploaded directly from the device.
	SystemInfo       *usagestats1.SystemInfo `protobuf:"bytes,8,opt,name=system_info" json:"system_info,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Checkin) Reset()         { *m = Checkin{} }
func (m *Checkin) String() string { return proto.CompactTextString(m) }
func (*Checkin) ProtoMessage()    {}

func (m *Checkin) GetAndroidId() int64 {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return 0
}

func (m *Checkin) GetBuildFingerprint() string {
	if m != nil && m.BuildFingerprint != nil {
		return *m.BuildFingerprint
	}
	return ""
}

func (m *Checkin) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *Checkin) GetBucketSnapshotMsec() int64 {
	if m != nil && m.BucketSnapshotMsec != nil {
		return *m.BucketSnapshotMsec
	}
	return 0
}

func (m *Checkin) GetBucketDurationMsec() int64 {
	if m != nil && m.BucketDurationMsec != nil {
		return *m.BucketDurationMsec
	}
	return 0
}

func (m *Checkin) GetCheckin() string {
	if m != nil && m.Checkin != nil {
		return *m.Checkin
	}
	return ""
}

func (m *Checkin) GetPackages() []*usagestats.PackageInfo {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *Checkin) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Checkin) GetSystemInfo() *usagestats1.SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

func init() {
}
